#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v25
# autospec commit: 9594167
#
Name     : R-labelled
Version  : 2.14.1
Release  : 76
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/labelled_2.14.1.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/labelled_2.14.1.tar.gz
Summary  : Manipulating Labelled Data
Group    : Development/Tools
License  : GPL-3.0
Requires: R-cli
Requires: R-dplyr
Requires: R-haven
Requires: R-lifecycle
Requires: R-rlang
Requires: R-stringr
Requires: R-tidyr
Requires: R-tidyselect
Requires: R-vctrs
BuildRequires : R-cli
BuildRequires : R-dplyr
BuildRequires : R-haven
BuildRequires : R-lifecycle
BuildRequires : R-memisc
BuildRequires : R-rlang
BuildRequires : R-stringr
BuildRequires : R-tidyr
BuildRequires : R-tidyselect
BuildRequires : R-vctrs
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
or 'Stata' with 'haven' or 'foreign'. This package
    provides useful functions to deal with "haven_labelled" and
    "haven_labelled_spss" classes introduced by 'haven' package.

%prep
%setup -q -n labelled
pushd ..
cp -a labelled buildavx2
popd
pushd ..
cp -a labelled buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1746627797

%install
export SOURCE_DATE_EPOCH=1746627797
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/labelled/DESCRIPTION
/usr/lib64/R/library/labelled/INDEX
/usr/lib64/R/library/labelled/Meta/Rd.rds
/usr/lib64/R/library/labelled/Meta/data.rds
/usr/lib64/R/library/labelled/Meta/features.rds
/usr/lib64/R/library/labelled/Meta/hsearch.rds
/usr/lib64/R/library/labelled/Meta/links.rds
/usr/lib64/R/library/labelled/Meta/nsInfo.rds
/usr/lib64/R/library/labelled/Meta/package.rds
/usr/lib64/R/library/labelled/Meta/vignette.rds
/usr/lib64/R/library/labelled/NAMESPACE
/usr/lib64/R/library/labelled/NEWS.md
/usr/lib64/R/library/labelled/R/labelled
/usr/lib64/R/library/labelled/R/labelled.rdb
/usr/lib64/R/library/labelled/R/labelled.rdx
/usr/lib64/R/library/labelled/WORDLIST
/usr/lib64/R/library/labelled/data/Rdata.rdb
/usr/lib64/R/library/labelled/data/Rdata.rds
/usr/lib64/R/library/labelled/data/Rdata.rdx
/usr/lib64/R/library/labelled/doc/index.html
/usr/lib64/R/library/labelled/doc/labelled.R
/usr/lib64/R/library/labelled/doc/labelled.Rmd
/usr/lib64/R/library/labelled/doc/labelled.html
/usr/lib64/R/library/labelled/doc/look_for.R
/usr/lib64/R/library/labelled/doc/look_for.Rmd
/usr/lib64/R/library/labelled/doc/look_for.html
/usr/lib64/R/library/labelled/doc/missing_values.R
/usr/lib64/R/library/labelled/doc/missing_values.Rmd
/usr/lib64/R/library/labelled/doc/missing_values.html
/usr/lib64/R/library/labelled/doc/packed_columns.R
/usr/lib64/R/library/labelled/doc/packed_columns.Rmd
/usr/lib64/R/library/labelled/doc/packed_columns.html
/usr/lib64/R/library/labelled/help/AnIndex
/usr/lib64/R/library/labelled/help/aliases.rds
/usr/lib64/R/library/labelled/help/figures/lifecycle-archived.svg
/usr/lib64/R/library/labelled/help/figures/lifecycle-defunct.svg
/usr/lib64/R/library/labelled/help/figures/lifecycle-deprecated.svg
/usr/lib64/R/library/labelled/help/figures/lifecycle-experimental.svg
/usr/lib64/R/library/labelled/help/figures/lifecycle-maturing.svg
/usr/lib64/R/library/labelled/help/figures/lifecycle-questioning.svg
/usr/lib64/R/library/labelled/help/figures/lifecycle-soft-deprecated.svg
/usr/lib64/R/library/labelled/help/figures/lifecycle-stable.svg
/usr/lib64/R/library/labelled/help/figures/lifecycle-superseded.svg
/usr/lib64/R/library/labelled/help/figures/logo.png
/usr/lib64/R/library/labelled/help/figures/logo.svg
/usr/lib64/R/library/labelled/help/labelled.rdb
/usr/lib64/R/library/labelled/help/labelled.rdx
/usr/lib64/R/library/labelled/help/paths.rds
/usr/lib64/R/library/labelled/html/00Index.html
/usr/lib64/R/library/labelled/html/R.css
/usr/lib64/R/library/labelled/tests/spelling.R
/usr/lib64/R/library/labelled/tests/testthat.R
/usr/lib64/R/library/labelled/tests/testthat/test-copy_labels.r
/usr/lib64/R/library/labelled/tests/testthat/test-labelled.r
/usr/lib64/R/library/labelled/tests/testthat/test-miscellanous.R
/usr/lib64/R/library/labelled/tests/testthat/test-na_values.R
/usr/lib64/R/library/labelled/tests/testthat/test-recode_if.r
/usr/lib64/R/library/labelled/tests/testthat/test-tagged_na.r
/usr/lib64/R/library/labelled/tests/testthat/test-to_labelled.r
/usr/lib64/R/library/labelled/tests/testthat/test-update_with.r
/usr/lib64/R/library/labelled/tests/testthat/test_lookfor.R
